version: '2.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - C:/2023_Kodlama/dockerVolumes/rentCarKeycloakVolume:/opt/keycloak/data

  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
#    networks:
#      - my-network
    volumes:
      - C:/2023_Kodlama/dockerVolumes/rentCarPostgreVolume:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
#    networks:
#      - my-network
    volumes:
      - C:\2023_Kodlama\dockerVolumes\rentCarMongoVolume:/data/db



  api-gateway:
    build: ./api-gateway
    #image: mehmetemre46/rentcarapigateway:version1.2
    ports:
      - 8020:8020
    mem_limit: 700m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#      - eureka.instance.prefer-ip-address=trued
#      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
#      - SPRING_CLOUD_GATEWAY_ROUTES_2_URI=http://discovery-service:8761
#      - SPRING_CLOUD_GATEWAY_ROUTES_3_URI=http://discovery-service:8761

#    depends_on:
#      - discovery-service



  discovery-service:
    build: ./discovery-server
    #image: mehmetemre46/rentcardiscoveryserver:version1.1
    ports:
      - 8761:8761
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address= true
    depends_on:
      - keycloak

  rental-service:
    build: ./rental-service
    #image: mehmetemre46/rentcarrentalservice:version1.5
    ports:
      - 7001:7001
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address=true
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
      - spring.datasource.url=jdbc:postgresql://postgres:5432/car-rental-service1
    depends_on:
      - postgres
      - discovery-service
      - api-gateway

  car-service:
    build: ./car-service
    #image: mehmetemre46/rentcarservice:version1.4
    ports:
      - 6001:6001
    mem_limit: 700m
    environment:
      - eureka.instance.prefer-ip-address=true
      - eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
      - spring.data.mongodb.uri=mongodb://root:root@mongodb:27017/carService?authSource=admin
    depends_on:
      - mongodb
      - discovery-service
      - api-gateway

networks:
  my-network:
    driver: bridge