services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - C:/2023_Kodlama/dockerVolumes/rentCarKeycloakVolume:/opt/keycloak/data

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      - C:/2023_Kodlama/dockerVolumes/rentCarPostgreVolume:/var/lib/postgresql/data

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - C:\2023_Kodlama\dockerVolumes\rentCarMongoVolume:/data/db

  api-gateway:
    image: mehmetemre46/rentcarapigateway:version1.2
    ports:
      - 8020:8020
    mem_limit: 700m
    networks:
      - my-network
#    depends_on:


  discovery-service:
    image: mehmetemre46/rentcardiscoveryserver:version1.1
    ports:
      - 8761:8761
    mem_limit: 700m
    networks:
      - my-network
    depends_on:
      - keycloak

  rental-service:
    image: mehmetemre46/rentcarrentalservice:version1.0
    ports:
      - 7001:7001
    mem_limit: 700m
    networks:
      - my-network
    depends_on:
      - postgres
      - discovery-service
      - api-gateway

  car-service:
    image: mehmetemre46/rentcarservice:version1.1
    ports:
      - 6001:6001
    mem_limit: 700m
    networks:
      - my-network
    depends_on:
      - mongodb
      - discovery-service
      - api-gateway

networks:
  my-network:
    driver: bridge