version: '2.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    mem_limit: 700m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - C:/2023_Kodlama/dockerVolumes/rentCarKeycloakVolume:/opt/keycloak/data

